### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by vnev** [ninebaobabs/questionable-snowmen#1]
Hey this is amazing work! I'm actually just starting to go through Casey's stream. I have a long way to go but I feel like I'll get there. My question to you is, when you started off with Casey's stream, how much knowledge of game programming in Windows did you already have? I am kind of going through this, and a lot of things like him making double buffers and things like that can get confusing. Is there anything you did to better understand these? 

Thanks!

**Comment by 0xbadb002** [comment]
Hey, I'm also intrigued about this!
@ninebaobabs

**Comment by ninebaobabs** [comment]
Hey, sorry I did not see your question earlier. I honestly did not think anyone would ever look at this. I'm not sure if an answer will still be helpful or not, but I'll add one anyway.

I had a decently good idea of game programming before (I had used Unity a bunch, and some other things). But I had very little understanding of windows and I still don't fully understand how windows buffers and device contexts and things work. To get this project to work I basically tried a bunch of things I found on stackoverflow until one worked, and took whatever little understanding I could from the discussion and the replies I found there. 

If I remember right, the big issue I was having was flickering once I added the text rendering. So to get around it I think I basically drew everything to a second offscreen buffer (which I probably set up wrong because all the colors seemed to get out of order) and then swapped that buffer in one frame late... but I'm not entirely sure to be honest. 

I still greatly enjoy Casey's streams and I wish I had the time to dedicate to studying them with the same fervor I did at the beginning, but I have become more selective in the ones I watch, and I have started to wish some of the information was better curated (thankfully they are now all wonderfully annotated at least). I think at the start I got a lot out of observing his style and perspective which was so fresh and new to me at the time and resonated on such a deep level. But I absorbed most of the value of that early on, and now it's only the concepts themselves I really come back for. The depth of his insight and knowledge is still second to none -- it's really like a personal mentor or something -- and I'm still so gratefully to him for what he's shared with us.

Sorry for the long-winded retrospective. We lonely programmers have to stick together you know. Hope you are doing well and still programming games! Cheers.
